---
- name: Converge
  hosts: all
  gather_facts: true
  vars:
    ard_kubevirt_namespace: test-namespace
    ard_deployment_name: ard-test-devstack-1
    ard_deployment_dir: /tmp/ard-test-deployment
    ard_kubevirt_ssh_access: loadbalancer
    ard_kubevirt_controller_service_ports:
      - name: ssh
        port: 22
        targetPort: 22
      - name: http
        port: 80
        targetPort: 80
      - name: https
        port: 443
        targetPort: 443
      - name: novnc
        port: 6080
        targetPort: 6080
    ard_nodes:
      - name: controller
        hostname: controller
        flavor: devstack-control
        image: debian-13
        groups:
          - controller
          - switch
      - name: compute-1
        hostname: compute-1
        flavor: devstack-compute
        image: debian-13
        groups:
          - compute
          - peers
  roles:
    - role: ard_provider_common
    - role: ard_kubevirt_inventory
