---
ard_render_networks:
  ard-mgmt:
    mode: nat
    provider_network: ard-mgmt
    mac_prefix: "52:54:00"
  datacenter:
    mode: isolated
    provider_network: datacenter
    mac_prefix: "52:54:00"
    mac_id: 130
