---
ard_render_node_classes:
  large:
    description: High-memory workload node, 16G target
  medium:
    description: Medium workload node, 8-12G-ish target
  default:
    description: Standard workload node, 8G target
  small:
    description: Small workload node, 4G target
  extra-small:
    description: Minimal test node, 1G target

ard_render_node_types:
  controller:
    class: large
    groups:
      - controller
      - switch
    profiles:
      - ssh
      - nested_virt
    flavor: devstack-control

  compute:
    class: default
    groups:
      - compute
      - peers
      - subnode
    profiles:
      - ssh
      - nested_virt
    flavor: devstack-compute

  microshift:
    class: medium
    groups:
      - microshift
    profiles:
      - ssh
      - nested_virt
    flavor: microshift-node
    image_var: ard_microshift_image_effective
