---
ard_render_services:
  devstack:
    devstack:
      common:
        run_devstack: true
        enable_ceph: false
        configure_vdpa: false
        external_bridge_mtu: 1450
        devstack_libvirt_type: kvm
        stack_user_password: tester
      controller:
        controller_localrc_extra: {}
        controller_local_conf_extra: {}
      compute:
        compute_localrc_extra: {}
        compute_local_conf_extra: {}
        compute_services_extra: {}
  ovn:
    node_profiles:
      - ovn
  tempest:
    devstack:
      common: {}
  ceph:
    node_profiles:
      - ceph
    devstack:
      common:
        enable_ceph: true
