---
ard_render_topologies:
  all-in-one:
    controller_count: 1
    compute_count: 0
    controller_runs_compute: true
  one-controller-one-compute:
    controller_count: 1
    compute_count: 1
    controller_runs_compute: true
  one-controller-two-compute:
    controller_count: 1
    compute_count: 2
    controller_runs_compute: false
