---
ard_render_schema_version: 1
ard_provider: libvirt
ard_provider_profile: local-libvirt
ard_target_branch: master
ard_topology: one-controller-one-compute
ard_service_profiles:
  - devstack
  - ovn
  - tempest
ard_libvirt_network_cidr: 192.168.96.0/24
