---
# tasks file for ensure_microshift
- name: configure crio
  become: true
  tags: crio
  block:
    - name: define crio stable repo
      get_url:
        url: "https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/{{crio_os}}/devel:kubic:libcontainers:stable.repo"
        dest: /etc/yum.repos.d/devel:kubic:libcontainers:stable.repo
        mode: '0440'
    - name: purge crio versioned repos
      shell: rm -f /etc/yum.repos.d/*:cri-o:*.repo
    - name: define crio versioned repos
      get_url:
        url: "https://download.opensuse.org/repositories/devel:kubic:libcontainers:stable:cri-o:{{crio_version}}/{{crio_os}}/devel:kubic:libcontainers:stable:cri-o:{{crio_version}}.repo"
        dest: "/etc/yum.repos.d/devel:kubic:libcontainers:stable:cri-o:{{crio_version}}.repo"
        mode: '0440'
    - name: install crio packages
      when: crio_install_type == 'rpm'
      package:
        name: "{{ item }}"
        state: present
      loop: "{{ crio_packages }}"
    - name: install crio packages with ostree
      when: crio_install_type == 'ostree'
      block:
        - name: check for installed crio versions
          command: crio --version
          failed_when: false
          register: _crio_check_result
        - name: uninstall crio to change requested version
          when: (not "crio version " + crio_version in _crio_check_result.stdout)
          command: rpm-ostree uninstall cri-o
        - name: install crio package
          command: rpm-ostree install {{ item }}
          register: _install_result
          loop: "{{ crio_packages }}"
          failed_when:
            - _install_result.rc != 0
            - ("is already requested" not in _install_result.stderr)
        - name: reboot the machine
          when:
            - ("systemctl reboot" in item.stdout)
          loop: "{{ _install_result.results }}"
          reboot:
    - name: ensure crio config snippets dir
      file:
        path: /etc/crio/crio.conf.d/
        state: directory
        owner: root
        mode: 0755
    - name: configure crio logging
      community.general.ini_file:
        path: /etc/crio/crio.conf.d/99-logging.conf
        section: crio.runtime
        option: "{{ item.key }}"
        value: "{{ item.value }}"
        mode: '0600'
      with_dict:
        - log_to_journald: "true"
        - log_level: "'{{ crio_log_level }}'"
    - name: fix CNI plugin config for crio
      copy:
        content: |
          {
              "cniVersion": "0.4.0",
              "name": "crio",
              "type": "bridge",
              "bridge": "cni0",
              "isGateway": true,
              "ipMasq": true,
              "hairpinMode": true,
              "ipam": {
                  "type": "host-local",
                  "routes": [
                      { "dst": "0.0.0.0/0" },
                      { "dst": "1100:200::/24" }
                  ],
                  "ranges": [
                      [{ "subnet": "10.85.0.0/16" }],
                      [{ "subnet": "1100:200::/24" }]
                  ]
              }
          }
        dest: /etc/cni/net.d/100-crio-bridge.conf
        mode: 0644
        owner: root
    - name: ensure drop-in dir for crio service
      file:
        path: /etc/systemd/system/crio.service.d
        state: directory
    - name: create drop-in for crio service
      copy:
        dest: /etc/systemd/system/crio.service.d/10-remove-microshift-overrides.conf
        content: |
          [Service]
          ExecStartPre=-/bin/rm -f /etc/crio/crio.conf.d/microshift.conf
    - name: enable crio service
      systemd:
        name: crio
        state: restarted
        daemon_reload: yes
        enabled: yes

- name: firewall-cmd
  when: manage_firewall|bool
  become: true
  shell: |
    firewall-cmd --zone=trusted --add-source=10.42.0.0/16 --permanent
    firewall-cmd --zone=public --add-port=80/tcp --permanent
    firewall-cmd --zone=public --add-port=443/tcp --permanent
    firewall-cmd --zone=public --add-port=5353/udp --permanent
    firewall-cmd --reload


# currnetly we are running this as root so that it has access to the crio socket but
# maybe we can run it as the {{ microshift_user }} user in the future if we add the {{ microshift_user }} user to
# the correct group?
- name: configure microshift
  when: microshift_install_type in ['podman', 'ostree']
  become: true
  #become_user: "{{ microshift_user }}"
  tags: microshift
  block:
    # - name: allow {{ microshift_user }} user systemd services to linger
    #   become: yes
    #   become_user: "{{ microshift_user }}""
    #   command: "loginctl enable-linger 1001"
    - name: remove  container
      when: microshift_upgrade|bool
      containers.podman.podman_container:
        name: microshift
        state: absent
    # we cant currently pass cgroups: no-common so we will use a systemd service file to run this instead
    #- name: Run container
    #  containers.podman.podman_container:
    #    privileged: yes
    #    name: microshift
    #    image: "{{microshift_image}}:{{microshift_tag}}"
    #    state: started
    #    volumes: "{{microshift_volumes}}"
    #    recreate: yes
    #    network: host
    #    restart_policy: on-failure
    #    cgroups: disabled
    - name: define microshift service
      template:
        src: microshift.service.j2
        dest: /etc/systemd/system/microshift.service
    - name: enable microshift service
      systemd:
        name: microshift
        state: restarted
        daemon_reload: yes
        no_block: true
        enabled: yes
      async: "{{ (not ansible_check_mode | bool) | ternary(300, omit) }}"
      poll: "{{ (not ansible_check_mode | bool) | ternary(0, omit) }}"
      register: _microshift_service_result
    - name: check microshift service status
      async_status:
        jid: "{{ _microshift_service_result.ansible_job_id }}"
      register: _microshift_service_wait_result
      until: _microshift_service_wait_result.finished
      retries: 30
      delay: 10
      when: not ansible_check_mode
    - name: install openshift clients
      ansible.builtin.unarchive:
        src: https://mirror.openshift.com/pub/openshift-v4/x86_64/clients/ocp/stable/openshift-client-linux.tar.gz
        dest: "{% if microshift_install_type == 'ostree' %}/usr/local/bin{% else %}/usr/bin{% endif %}"
        remote_src: yes
    - name: setup kubconfig for {{ microshift_user }} user
      when: microshift_install_type != 'ostree'
      become: true
      shell: |
        mkdir -p /home/{{ microshift_user }}/.kube
        chown {{ microshift_user }}:{{ microshift_user }} /home/{{ microshift_user }}/.kube
        podman cp microshift:/var/lib/microshift/resources/kubeadmin/kubeconfig /home/{{ microshift_user }}/.kube/config
        chown {{ microshift_user }}:{{ microshift_user }} /home/{{ microshift_user }}/.kube/config
    - name: setup kubconfig for {{ microshift_user }} user
      when: microshift_install_type == 'ostree'
      shell: |
        mkdir -p /var/lib/{{ microshift_user }}/.kube
        chown {{ microshift_user }}:{{ microshift_user }} /var/lib/{{ microshift_user }}/.kube
        podman cp microshift:/var/lib/microshift/resources/kubeadmin/kubeconfig /var/lib/{{ microshift_user }}/.kube/config
        chown {{ microshift_user }}:{{ microshift_user }} /var/lib/{{ microshift_user }}/.kube/config

- name: configure microshift
  when: microshift_install_type == 'rpm'
  become: true
  tags: microshift
  block:
    - name: enable copr repo
      community.general.copr:
        state: enabled
        name: '@redhat-et/microshift'
    - name: install microshift package
      package:
        name: microshift
        state: present
    - name: enable microshift service
      systemd:
        name: microshift
        state: restarted
        enabled: yes
        daemon_reload: yes
    - name: install openshift clients
      ansible.builtin.unarchive:
        src: https://mirror.openshift.com/pub/openshift-v4/x86_64/clients/ocp/stable/openshift-client-linux.tar.gz
        dest: /usr/bin
        remote_src: yes
    - name: setup kubconfig for {{ microshift_user }} user
      shell: |
        mkdir -p /home/{{ microshift_user }}/.kube
        chown {{ microshift_user }}:{{ microshift_user }} /home/{{ microshift_user }}/.kube
        cat /var/lib/microshift/resources/kubeadmin/kubeconfig > /home/{{ microshift_user }}/.kube/config
        chown {{ microshift_user }}:{{ microshift_user }} /home/{{ microshift_user }}/.kube/config

# NOTE(sean-k-mooney): we may want to pin the olm version instead of using latest.
- name: install olm
  when: install_olm | bool
  tags: olm
  become_user: "{{ microshift_user }}"
  become: true
  block:
    - name: install git
      become: true
      become_user: root
      package:
        name: git
        state: present
    - name: clone operator-sdk
      ansible.builtin.git:
        repo: '{{operator_sdk_url}}'
        dest: '{{repo_dir}}/operator-sdk'
        version: '{{operator_sdk_version}}'
    - name: install go
      become: true
      become_user: root
      package:
        name: golang
        state: present
    - name: build  sdk
      shell:
        cmd: make build
        chdir: '{{repo_dir}}/operator-sdk'
    - name: check if olm is installed
      shell:
        cmd: build/operator-sdk olm status
        chdir: '{{repo_dir}}/operator-sdk'
      register: olm_status
      failed_when:
        - olm_status.rc != 0
        - '"Failed to get OLM status: error getting installed OLM version" not in olm_status.stderr'
    - name: install olm with sdk
      when:
        - olm_status.rc != 0
      shell:
        cmd: build/operator-sdk olm install
        chdir: '{{repo_dir}}/operator-sdk'

- name: install local path provisioner
  when: install_lpp | bool
  tags: lpp
  become_user: "{{ microshift_user }}"
  become: true
  block:
    - name: create storage path dir
      become: true
      become_user: root
      file:
        path: '/opt/local-path-provisioner'
        mode: '777'
        state: directory
      register: local_path_directory
    - name: Download local-path-provisioner manifests
      when: local_path_directory.changed
      get_url:
        url:  https://raw.githubusercontent.com/rancher/local-path-provisioner/v0.0.22/deploy/local-path-storage.yaml
        dest: "/home/{{ microshift_user }}/local-path-storage.yaml"
        mode: '0440'
    - name: copy manifest patch
      when: local_path_directory.changed
      copy:
        src: local-path.patch
        dest: "/home/{{ microshift_user }}/local-path.patch"
    - name: install local-path-provider
      when: local_path_directory.changed
      shell:
        cmd: |
          cat local-path.patch | patch -p1 local-path-storage.yaml
          kubectl apply -f local-path-storage.yaml
        chdir: /home/{{ microshift_user }}

