---
ard_provider: libvirt
ard_deployment_name: molecule-octc
ard_resource_name_prefix: ard-molecule-octc

ard_topology: one-controller-two-compute
ard_default_image: debian-13
ard_default_controller_flavor: devstack-control
ard_default_compute_flavor: devstack-compute
ard_default_vm_preference: devstack

ard_libvirt_network_name: ard-molecule-octc
ard_libvirt_network_cidr: 192.168.97.0/24
ard_libvirt_network_gateway: 192.168.97.1
