---
- name: Converge
  hosts: all
  pre_tasks:
    - name: Install role dependencies
      ansible.builtin.shell: |
        apt-get update
        apt-get install -y --no-install-recommends ca-certificates curl sudo
      changed_when: false

  tasks:
    - name: Include ensure_kustomize
      ansible.builtin.include_role:
        name: ensure_kustomize
