---
ard_provider: libvirt
ard_deployment_name: molecule-stable-2026-1
ard_resource_name_prefix: ard-molecule-stable-2026-1

ard_topology: one-controller-one-compute
ard_default_image: ubuntu-24.04
ard_default_controller_flavor: devstack-control
ard_default_compute_flavor: devstack-compute
ard_default_vm_preference: devstack

ard_libvirt_network_name: ard-molecule-stable-2026-1
ard_libvirt_network_cidr: 192.168.98.0/24
ard_libvirt_network_gateway: 192.168.98.1
