---
ard_nodes:
  - name: controller
    hostname: controller
    provider_resource_name: ard-molecule-stable-2026-1-controller
    groups:
      - controller
      - switch
    image: ubuntu-24.04
    flavor: devstack-control
    preference: devstack
    networks:
      - name: ard-mgmt
        ip: 192.168.98.2
        mac: "52:54:00:98:00:02"
    profiles:
      - ssh
      - nested_virt
      - ovn
  - name: compute1
    hostname: compute1
    provider_resource_name: ard-molecule-stable-2026-1-compute1
    groups:
      - compute
      - peers
      - subnode
    image: ubuntu-24.04
    flavor: devstack-compute
    preference: devstack
    networks:
      - name: ard-mgmt
        ip: 192.168.98.3
        mac: "52:54:00:98:00:03"
    profiles:
      - ssh
      - nested_virt
      - ovn
