---
dependency:
  name: galaxy
  enabled: false
driver:
  name: default
provisioner:
  name: ansible
  env:
    ANSIBLE_STDOUT_CALLBACK: yaml
  ard:
    provider: libvirt
    provider_profile: local-libvirt
    deployment_name: molecule-default
    resource_name_prefix: ard-molecule-default
    target_branch: master
    topology: one-controller-one-compute
    service_profiles:
      - devstack
      - ovn
      - tempest
    libvirt:
      network_name: ard-molecule-default
      network_cidr: 192.168.97.0/24
verifier:
  name: ansible
scenario:
  test_sequence:
    - dependency
    - destroy
    - syntax
    - create
    - converge
    - verify
    - destroy
  create_sequence:
    - dependency
    - create
  destroy_sequence:
    - dependency
    - destroy
