galaxy_info:
  author: ard contributors
  description: Install operator development tooling on a RedHat/CentOS MicroShift host
  license: Apache-2.0

  min_ansible_version: "2.14"

  platforms:
    - name: EL
      versions:
        - "9"

  galaxy_tags:
    - openstack
    - operator
    - golang
    - microshift

dependencies: []
