FROM docker.io/library/debian:13

ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update \
    && apt-get install -y --no-install-recommends \
       bash \
       git \
       make \
       python3 \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*
