---
- name: Converge
  hosts: all
  pre_tasks:
    - name: Install sudo for become support
      ansible.builtin.shell: |
        apt-get update
        apt-get install -y --no-install-recommends sudo
      changed_when: false

  tasks:
    - name: Include prepare_dev_tools
      ansible.builtin.include_role:
        name: prepare_dev_tools
