---
- name: Prepare MicroShift hosts
  hosts: "{{ microshift_target_hosts | default('microshift') }}"
  gather_facts: true
  roles:
    - microshift_defaults
    - ensure_stack_user
    - microshift_prereqs
    - microshift_repos
    - microshift_install_rpm
    - microshift_addons
    - microshift_validate

- name: Print MicroShift debug connection details
  hosts: all
  gather_facts: false
  roles:
    - print_debug_ip
