---
- name: Setup DUT
  hosts: all
  tasks:
    - name: Update package cache
      become: true
      ansible.builtin.package:
        update_cache: true
    - name: Install required packaged
      become: true
      package:
        name: "{{ item }}"
        state: present
      with_items:
        - acl
        - python3-pip