---
# tasks file for ensure_stack_user
- name: create stack user as root
  become: yes
  tags: users
  vars:
    devstack_user: stack
  block:
    - name: Create user
      become: true
      ansible.builtin.user:
        name: "{{ devstack_user }}"
        password: "{{ stack_user_password | password_hash('sha512','A512') }}"
        home: /opt/stack
        create_home: true
        state: present
        shell: /bin/bash

    - name: Add user to sudoers with NOPASSWD
      become: true
      ansible.builtin.lineinfile:
        path: /etc/sudoers.d/50_stack_user
        create: true
        mode: "0440"
        line: "{{ devstack_user }} ALL=(ALL) NOPASSWD:ALL"
        validate: "visudo -cf %s"

- name: generate stack user ssh key "{{ssh_key_filename}}"
  delegate_to: 127.0.0.1
  run_once: yes
  tags: ssh
  community.crypto.openssh_keypair:
    path: "~/.ssh/{{ssh_key_filename}}"
    type: ed25519
    state: present
    mode: '0600'
    force: no

- name: "Read {{ ssh_key_filename }} pub key"
  tags: ssh
  delegate_to: 127.0.0.1
  ansible.builtin.slurp:
    src: "~/.ssh/{{ssh_key_filename}}.pub"
  register: _ssh_key_filename_content

- name: Read authorized_keys
  tags: ssh
  ansible.builtin.slurp:
    src: .ssh/authorized_keys
  register: _user_authorized_keys

- name: setup stack user ssh keys
  become_user: stack
  become: yes
  tags: ssh
  block:
    - name: create .ssh dir
      file:
        path: '~/.ssh'
        state: directory
    - name: copy private key
      copy:
        src: "~/.ssh/{{ssh_key_filename}}"
        dest: "~/.ssh/id_ed25519"
        mode: '0600'
    - name: copy public key
      copy:
        src: "~/.ssh/{{ssh_key_filename}}.pub"
        dest: "~/.ssh/id_ed25519.pub"

    - name: Set authorized key
      ansible.posix.authorized_key:
        user: stack
        state: present
        key: "{{ _user_authorized_keys.content | b64decode + _ssh_key_filename_content.content | b64decode }}"

- name: setup root user ssh keys
  become: yes
  tags: ssh
  block:
    - name: create .ssh dir
      file:
        path: '~/.ssh'
        state: directory
    - name: copy private key
      copy:
        src: "~/.ssh/{{ssh_key_filename}}"
        dest: "~/.ssh/id_ed25519"
        mode: '0600'
    - name: copy public key
      copy:
        src: "~/.ssh/{{ssh_key_filename}}.pub"
        dest: "~/.ssh/id_ed25519.pub"
    - name: Set authorized key
      ansible.posix.authorized_key:
        user: root
        state: present
        key: "{{ _user_authorized_keys.content | b64decode + _ssh_key_filename_content.content | b64decode }}"

- name: setup ansible user ssh keys
  tags: ssh
  block:
    - name: create .ssh dir
      file:
        path: '~/.ssh'
        state: directory
    - name: copy private key
      copy:
        src: "~/.ssh/{{ssh_key_filename}}"
        dest: "~/.ssh/id_ed25519"
        mode: '0600'
    - name: copy public key
      copy:
        src: "~/.ssh/{{ssh_key_filename}}.pub"
        dest: "~/.ssh/id_ed25519.pub"
    - name: Set authorized key
      ansible.posix.authorized_key:
        user: "{{ ansible_user }}"
        state: present
        key: "{{ _user_authorized_keys.content | b64decode + _ssh_key_filename_content.content | b64decode }}"

- name: update ansible_user
  tags: always
  when: update_ansible_user
  block:
    - name: print currnet config
      debug:
        msg: |
          ansible_user: {{ansible_user| default('unset')}}
          remote_user: {{remote_user | default('unset')}}
    - name: set ansible_user
      set_fact:
        ansible_user: stack
        ansible_private_key_file: "~/.ssh/{{ssh_key_filename}}"
    - name: print currnet config
      debug:
        msg: |
          ansible_user: {{ansible_user| default('unset')}}
          remote_user: {{remote_user | default('unset')}}
