---
- name: Verify
  hosts: all
  gather_facts: false
  tasks:
    - name: Assert podman-backed host was provisioned
      ansible.builtin.assert:
        that:
          - ansible_connection == 'podman'
          - inventory_hostname == 'print-debug-ip-default'
