---
- name: deploy minishift to openshift hosts
  hosts: openshift
  tags: openshift
  roles:
    - ensure_stack_user
    - ensure-podman
- name: deploy minishift to openshift hosts
  hosts: openshift
  tags: openshift
  remote_user: stack
  roles:
    - ensure_kustomize
    - ensure_microshift

- name: finalize
  hosts: all
  roles:
    - print_debug_ip
