---
- name: basic setup
  hosts: all
  tags: common
  roles:
    - ensure_stack_user

- name: deploy openshift
  hosts: openshift
  tags: ocp
  roles:
    - ensure_crc
    - ensure_kustomize

- name: finalize
  hosts: all
  roles:
    - print_debug_ip

