---
- name: Converge
  hosts: all
  gather_facts: true
  vars:
    ard_kubevirt_namespace: test-namespace
    ard_stack_public_key: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAItest molecule-test
    ard_deployment_name: smooney-devstack-1
    ard_deployment_dir: /tmp/ard-test-deployment
    ard_nodes:
      - name: controller
        hostname: controller
        flavor: devstack-control
        image: debian-13
        groups:
          - controller
          - switch
      - name: compute-1
        hostname: compute-1
        flavor: devstack-compute
        image: debian-13
        groups:
          - compute
          - peers
  roles:
    - role: ard_provider_common
    - role: ard_kubevirt_node
