---
- import_playbook: ../../ansible/playbooks/workloads/microshift/converge.yaml
  vars:
    ard_project_dir: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') | default(playbook_dir ~ '/../..', true) }}"
    ard_scenario_dir: "{{ lookup('env', 'MOLECULE_SCENARIO_DIRECTORY') | default(playbook_dir, true) }}"
    ard_deployment_dir: "{{ ard_scenario_dir }}/deployment"
    ard_local_vars_file: >-
      {{ lookup('ansible.builtin.first_found',
          {'files': [ard_scenario_dir ~ '/local-vars.yaml',
                     ard_deployment_dir ~ '/local-vars.yaml',
                     ard_project_dir ~ '/local-vars.yaml'],
           'skip': true}) }}
